#!/bin/sh
#
# The Qubes OS Project, http://www.qubes-os.org
#
# Copyright (C) 2017  Andrew Morgan <andrew@amorgan.xyz>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#

set -eu

if ! [ $# = 1 ] ; then
    echo "Usage: $(basename ${0}) filename"
	exit 1
fi

# Check if this is an untrusted file
if qvm-file-trust -q "${1}" ; then
    echo \
"This file is not untrusted. Please first mark it as such with qvm-file-trust."
    exit 0
fi

# Attempt to 'unlock' file for read permissions
ORIG_PERMISSIONS=$(stat -c "%a" "${1}")
chmod 0644 "${1}"

# Open in disposableVM
bash qvm-open-in-vm '$dispvm' "${1}"

# Mark the file as untrusted once again
qvm-file-trust -u -q "${1}"
